### ISSUE TITLE
Add Bedrock Support

### ISSUE THREAD

**Issue by Miniontoby** [mc-build/lang-mc#18]
Hi,

It would be nice to have a way to also build an addon for bedrock from the same .mc file

The code won't need a huge amount of changes.
- Change the location of the tick.json and load.json files, moving the function file locations and references (since there are no namespaces in BE -> `my_namespace:tick` -> `my_namespace/tick` which is located at `./functions/my_namespace/tick.mcfunction` instead of `./data/my_namespace/functions/tick.mcfunction`).
- fake scoreboard 'playernames' should be surrounded by double quotes (or at least names like `$ajacent_blocks`. Example: `scoreboard players set $adajent_blocks myscoreboard 0`->`scoreboard players set "$adajent_blocks" myscoreboard 0` [solution (which idk where to put): `str.replace(/scoreboard players ([^ ]+) ([^" ]+) ([^ ]+) ([0-9]+)/g, 'scoreboard players $1 "$2" $3 $4');`])
- Same for `@e[tag=0]` where the tag value is numeric, should also be surrounded by double quotes -> `@e[tag="0"]`
- selector keywords replace: `distance` -> `r` and `limit` -> `c`
- `@e[sort=random]` should become `@r`
- pack.mcmeta -> manifest.json

and possibly also some others

Update: I have made a little start at https://github.com/Miniontoby/lang-mc/tree/bedrock-stable - It only does the first point of the list

- Miniontoby

**Comment by IanSSenne** [comment]
hi @Miniontoby, is this something your still interested in seeing mc-build support? if so please reach out and let me know, this codebase won't be receiving any major changes at this point but I'm open to discussing this for future upcoming versions of the mc-build project.

**Comment by Miniontoby** [comment]
Yes I would still like this to be some kind of part of the project
